In [43]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

In [21]:
df = pd.read_csv('tracking.csv')

In [ ]:
df2 = df.loc[:,['Fare','SibSp','Parch','Sex']]

In [23]:
df.head(5)

home  how_it_works  contact  bought
0     1             1        0       0
1     1             1        0       0
2     1             1        0       0
3     1             1        0       0
4     1             1        0       0

In [ ]:
##features
# principal (home); a how it works, que explica o funcionamento do site; e contact, para entrar em contato
##home - se o usuario acessou a pagina ou nao | 0 nao acessou , 1 acessou
##bought - variavel resposta - se comprou ou nao 

In [27]:
x = df.loc[:,['home','how_it_works','contact']]
y = df.loc[:,'bought']

lr = LogisticRegression()

lr.fit(x, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
y_pred = lr.predict(x)

In [29]:
y_predp = lr.predict_proba(x)[:,1]

In [30]:
print(y_pred)

[0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 1 1 1
 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 1 0 1 0 1 0 1 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 0 0 0]


In [31]:
print(y_predp)

[0.18618695 0.18618695 0.18618695 0.18618695 0.18618695 0.82176592
 0.18618695 0.82176592 0.18618695 0.82176592 0.18618695 0.82176592
 0.13520657 0.13520657 0.13520657 0.13520657 0.13520657 0.00769833
 0.13520657 0.00769833 0.13520657 0.00769833 0.13520657 0.00769833
 0.82176592 0.71533488 0.71533488 0.82176592 0.00769833 0.13520657
 0.00769833 0.82176592 0.13520657 0.82176592 0.82176592 0.82176592
 0.82176592 0.13520657 0.18618695 0.82176592 0.00769833 0.13520657
 0.00769833 0.82176592 0.13520657 0.13520657 0.82176592 0.82176592
 0.18618695 0.18618695 0.18618695 0.18618695 0.82176592 0.18618695
 0.82176592 0.18618695 0.82176592 0.18618695 0.82176592 0.13520657
 0.82176592 0.00769833 0.13520657 0.00769833 0.82176592 0.07852147
 0.13520657 0.82176592 0.82176592 0.18618695 0.18618695 0.13520657
 0.13520657 0.13520657 0.13520657 0.00769833 0.13520657 0.00769833
 0.13520657 0.18618695 0.13520657 0.13520657 0.13520657 0.82176592
 0.82176592 0.18618695 0.18618695 0.13520657 0.13520657 0.8217

In [32]:
lr.coef_

array([[ 3.38404473, -0.60692052,  2.39641674]])

In [33]:
lr.intercept_

array([-4.25210363])

In [36]:
confusion_matrix(y, y_pred)

array([[66,  0],
       [ 3, 30]], dtype=int64)

In [44]:
accuracy_score(y,y_pred)

0.9696969696969697

In [47]:
coeficientes = pd.Series({i[0]: i[1] for i in zip(['home', 'how_it_works', 'contact'], lr.coef_[0])})
coeficientes

home            3.384045
how_it_works   -0.606921
contact         2.396417
dtype: float64

In [46]:
df.head()

home  how_it_works  contact  bought
0     1             1        0       0
1     1             1        0       0
2     1             1        0       0
3     1             1        0       0
4     1             1        0       0

In [48]:
log_odds = lr.intercept_ \
+ x.loc[1, 'home']*coeficientes['home'] \
+ x.loc[1, 'how_it_works']*coeficientes['how_it_works'] \
+ x.loc[1, 'contact']*coeficientes['contact'] \

odds = np.exp(log_odds)
p = odds/(1 + odds)
p#é a probabilidade do evento occorer, alguem comprar

array([0.18618695])